### ISSUE TITLE
Is this need rooted device?

### ISSUE THREAD

**Issue by XuNeal** [crmulliner/ddi#11]
I see it do "su" before run hijack. Is that mean the device must be rooted? I want use this technique in my app. And do the steps (copy *.so, get pid, run hijack) in a subclass of Application in my APP. But my customer's device may not be rooted. Is this possible to do that?

**Comment by t0kt0ckus** [comment]
A rooted device is a strict requirement, at least for any AOS version that limits access to the ptrace API, which may be any reasonably recent version. So even if you manage to work around the file permissions issues, hijack will fail to inject the shared library into the target process.

**Comment by XuNeal** [comment]
thx for commented, What did you say is very simple to understand, I shoud think that myself.
