### ISSUE TITLE
Unable to resolve the class of a test app

### ISSUE THREAD

**Issue by albertocoletta** [crmulliner/ddi#4]
Hi Collin, 
thanks for the great work!
I'm trying to hook a method of a very simple test app, but dalvik_hook can't resolve its class.
I checked many times that the name is correct (even in the smali code) but it just can't hook it.
I added in the code some log debug strings. I tried this code with different android versions: 2.3.3, 4.1.2, 4.2.2, 4.3.
Could you please help me?
All the code (including the log) is here: https://github.com/boh717/ddi-testing

**Comment by albertocoletta** [comment]
I've already saw the other open issue and I think these are related.
I've also tried to set: dalvik_dump_class(&d, NULL); and the app crashes as soon as starts.

**Comment by aosti** [comment]
Hello, I'm also using the framework and had the same problem. Try dalvik_dump_class(&d, "") instead of dalvik_dump_class(&d, NULL).

**Comment by cebernalc** [comment]
Is there a solution for this?
