### ISSUE TITLE
Compilation erros: -Werror=format-security

### ISSUE THREAD

**Issue by t0kt0ckus** [crmulliner/ddi#5]
Both `/ddi/examples/strmon/jni/mon.c` and `/ddi/examples/smsdispatch/jni/smsdispatch.c` cause compilation errors (on latest NDK toolchains):

```
ddi/examples/strmon/jni/mon.c: In function 'my_log':
ddi/examples/strmon/jni/mon.c:47:2: error: format not a string literal and no format arguments [-Werror=format-security]
ddi/examples/strmon/jni/mon.c: In function 'my_log2':
ddi/examples/strmon/jni/mon.c:52:3: error: format not a string literal and no format arguments [-Werror=format-security]
```

```
ddi/examples/smsdispatch/jni/smsdispatch.c: In function 'my_log':
ddi/examples/smsdispatch/jni/smsdispatch.c:49:2: error: format not a string literal and no format arguments [-Werror=format-security]
ddi/examples/smsdispatch/jni/smsdispatch.c: In function 'my_log2':
ddi/examples/smsdispatch/jni/smsdispatch.c:54:3: error: format not a string literal and no format arguments [-Werror=format-security]
```

We can work around these errors by adding `LOCAL_DISABLE_FORMAT_STRING_CHECKS := true` to the modules' Android.mk.
Though, I'm quite sure @jduck will soon properly fix `mon.c` and `smsdispatch.c`.

**Comment by jduck** [comment]
I fixed them (and other issues) but have to do a pull request because I don't have commit access to this repo =)

**Comment by jduck** [comment]
The fixes are merged, but I can't close this ticket since I don't have the required access !

**Comment by t0kt0ckus** [comment]
@jduck, thanks.
